name: BongoCat Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Generate changelog
        id: create_release
        run: npx changelogithub --draft --name ${{ steps.vars.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  build-app:
    needs: create-release
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install rust target
        run: rustup target add aarch64-apple-darwin

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: target

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install front-end dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the app
        run: pnpm tauri build --target aarch64-apple-darwin
        env:
          CI: false
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: bundle-dmg
          path: target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
          if-no-files-found: error

      - name: Upload tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: bundle-tar
          path: target/aarch64-apple-darwin/release/bundle/macos/*.tar.gz
          if-no-files-found: error

      - name: Upload .sig
        uses: actions/upload-artifact@v4
        with:
          name: bundle-sig
          path: target/aarch64-apple-darwin/release/bundle/macos/*.sig
          if-no-files-found: warn

  publish-release:
    needs: [create-release, build-app]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.RELEASE_TOKEN }}
          draft: false
          prerelease: false
          files: bundle-*/*
